- components/layer1.md
- layer-1-contracts/README.md
Based on a conversation with @andrewgordstewart today, adds a set of design goals for the L1 contracts.
**Additional context**
We identified these goals as explicit decisions to be made which would unblock the majority of work on the bisection game.
Fixes ENG-1309
> Add design goals for L1 contracts

- components/fraud-proof-vm/fraud_proof_program.md
- components/fraud-proof-vm/fraud_proof_vm.md
Adds an updated description of the fraud proof VM and the program which is run inside of the fraud proof VM during a fraud proof.
Credit to @ben-chain for the sub-process concept - it does make conceptualizing the fraud proof much cleaner.
> Add fraud proof VM & program writeup

- .gitignore
- .markdownlint.json
Updated the lint rules to use `stern: true` instead of `strict: true` option for `MD013 - Line length`. I.e. only warn about line-length when there is white-space after the limit. Long URLs are not a problem.
And also added a `.gitignore` to not depend on global user gitignore for ignoring `node_modules` when installing/running the linter locally.
> .gitignore and lint line-length fix

- .gitignore
- .markdownlint.json
- exec-engine.md
This specs:
- The relation of deposits to the execution engine
- The Engine API, with the `transactions` field 
- Networking on engine side (different from rollup p2p PR, separate thing): no modification, but light configuration to be aware of
- Two types of sync the engine can operate with. Refer to rollup-node/driver for the block-by-block worst case. Spec happy-case abstractly (we re-use existing L1 behavior).
> Spec Execution Engine behavior

- .github/workflows/go-ci.yml
- .github/workflows/lint.yml
- meta/linting.md
- opnode/main.go
- opnode/node/driver.go
- opnode/node/log.go
- opnode/node/node.go
Changes:
- Run linting on `staging` branch
- Go linting in CI
- Go test in CI
- Update linting meta doc how to run Go linter locally
- Fix go code: fix dead return statements, single-case select, empty else.
Edit (force push): forgot goimports in CI config
> ci: golang linting and testing

- glossary.md
- rollup-node.md
- Addresses https://github.com/ethereum-optimism/optimistic-specs/issues/47 (specify errors)
- Explains sync better.
- Add links to new specification files.
> Rollup node spec fixes

- packages/contracts/contracts/L1/DepositFeed.sol
- packages/contracts/test/L1/DepositFeed.spec.ts
- specs/deposits.md
Replaces the `value` argument of the `TransactionDeposited` event, and Deposit Transaction type with two arguments:
1. `depositValue` is the ETH amount sent to the contract, to be minted on L2.
2. `sendValue` is the ETH amount to be sent to the recipient (analogous to `value` in s a typical L1 transaction).
> Split 'value' into 'mint' and 'value'

- packages/contracts/package.json
A very small change to add a missing yarn command, so that we can run `yarn build` in the specs dir.
> Add a build command to package.json

- packages/contracts/contracts/L1/DepositFeed.sol
- packages/contracts/contracts/L2/L1Block.sol
- packages/contracts/test/L1/DepositFeed.spec.ts
- packages/contracts/test/L2/L1Block.spec.ts
Uses solidity's new [custom errors](https://docs.soliditylang.org/en/latest/contracts.html#errors) instead of reason strings, this approach saves gas and IMO is cleaner.
This PR builds on #108, otherwise they would conflict.
> Use custom solidity errors

- specs/README.md
Adds a minimal README file to the specs directory, outlining the design goals. 
It could be argued that this file should include more information, such as usage info for installing or linting, but that should be separate PR.
**Metadata**
- Fixes #82
> specs: Add README with design goals

- go.mod
- go.sum
- opnode/eth/canonical.go
- opnode/eth/heads.go
- opnode/eth/id.go
- opnode/eth/source.go
This:
- Introduces different types of `Source` interfaces: abstract away the JSON RPC from the ref impl. And more granular than e.g. the `ethereum.ChainReader`
- Simple combined-source: to support multiple L1 sources (can replace with smarter load-balancing later on)
- Wrap a header subscription to provide a channel of `HeadSignal` updates. Used to track L1 and L2 chain (requires websocket RPC, note that `staging` does have a fallback)
- `BlockID`: combine hash and height, makes the sync implementation more readable
**Depends on #124**
Review: any team. No specs affected other than defining `BlockID`. Sources are named based on Go-ethereum method naming.
> ref impl: eth utils - watch head, hash/height id type, RPC source interfaces

- go.mod
- go.sum
- opnode/l2/api.go
This:
- Defines some types like `Bytes32` and `Bytes256` for stricter API decoding
- Implements client-bindings for the https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md
- Implements the backwards-compatible API change that the optimism spec defines (`transactions` field in payload request attributes)
- Logs extensively for debugging (note: staging branch was logging to the wrong logger, it now logs to the `el.Log` instead of global geth log)
- Helper function to convert a block to an execution payload (for completeness, might remove this later)
**Depends on #125**
Review: any team. No spec changes required, implements existing engine API spec.
> ref impl: Engine API client bindings

- go.mod
- opnode/l2/input_derivation.go
- opnode/l2/input_derivation_test.go
- opnode/l2/reading.go
- opnode/l2/reading_test.go
This:
- Defines receipts to user deposits conversion
- Defines L1-info to deposit conversion
- Defines how to combine these deposits into payload attributes
- Test user-deposits
- Test l1-info deposits
- *(not tested, except in e2e): concatenating above deposits into payload attributes*
- Defines the inverse process of L1-info deposit: part of sync requires us to read which L1 info was last processed on L2, we simply parse the last L1-info transaction.
**Depends on #127**
Review: any team. No wild changes required, but naming is inconsistent, and we can try cross-referencing the functions. And should the inverse process (reading L1 info deposits) be specified as well, or is it implicitly defined already?
This took more dev iteration on staging, …
> ref impl: input derivation and reading l1-info

- opnode/l2/driver_step.go
- opnode/l2/output_derivation.go
This:
- Implements the retrieval of output full execution-payload when given the payload-attributes (inputs)
- Implements how a L2 chain extends with a block: L1 data is retrieved, the input-derivation is called, the output-derivation is called, the payload is executed, and the forkchoice is updated 
**Depends on #128**
Review: any team.
Regarding testing: this code mostly strings together consecutive API calls, but there is little branching (aside from API error handling). Any suggestions how to best test this? End-to-end for API is verified to work, but no neat unit-test yet.
> ref impl: derive outputs and run driver step

- opnode/l2/sync_reference.go
- opnode/l2/sync_start.go
- opnode/l2/sync_start_test.go
- specs/exec-engine.md
- specs/rollup-node.md
This:
- Implements a "sync reference" interface, and implementation that implements it based on common RPC source interfaces. To mock chain status easily for sync starting-point testing.
- Implements algorithm from @karlfloersch (with missing edge cases handled) to find the starting point for sync, statelessly (i.e. no rollup-node storage requirement, nor in-memory chain/tree)
**Depends on #129**
Review: any team.
Spec (TODO): update reference how we find the starting point of sync.
Testing: ~~different starting point edge cases~~ done
> ref impl: find starting point of sync, given L1 and L2 interfaces

- go.mod
- go.sum
- opnode/internal/testlog/LICENSE
- opnode/internal/testlog/README.md
- opnode/internal/testlog/testlog.go
- opnode/l2/driver.go
- opnode/l2/driver_loop.go
- opnode/l2/driver_state.go
- opnode/l2/driver_state_test.go
- opnode/l2/sync_start.go
- opnode/l2/sync_start_test.go
- specs/rollup-node.md
This:
- `EngineDriver` is like a binding to a remote engine, tracking to where it's synced.
- `Drive` is a sync process that can be started/shutdown **per remote engine**, and responds to head events from L1, and syncs (happy extend-case, or worst-case sync with reorg) the L2 chain by running a driver-step on the right starting-point. There is only a single active driving process at a time per engine.
**Depends on #130**
Review: any team, systems team preferred.
Spec: Do we want to go-indepth, like back-off strategy and failure-cases of sync in the spec? Or maybe just the "if out of sync, run a driver-step on with L1 block `X_n` and L2 block parent `Y_{n-1}`" summary of driver routine behavior? (we already more or less have the latter)
Testing: this …
> ref impl: driver agent: respond to head events and stay in sync

- go.mod
- go.sum
- opnode/cmd/main.go
The start, command parsing, shutdown handling, etc. is a lot of boilerplate that is common between all usages of `ask`, so I moved it into the library as convenience method.
> ref impl: reduce command running boilerplate

- .editorconfig
Adds a basic `.editorConfig`, identical to the one in the [monorepo](https://github.com/ethereum-optimism/optimism/blob/d10e31996aca39bc9529dcbe69a57aa46e6a84e9/.editorconfig#L1). 
This will pretty much eliminate any issues with extra whitespace creeping in at EOL, resulting in 'dirty' commits.
Many editors will inherit settings from this file, but VSCode requires an [extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) to support it. 
Learn more: https://editorconfig.org/.
> chore: add basic editorconfig file

- .gitignore
- Dockerfile.opnode
- Makefile
- Adds a Dockerfile so that we can build opnode images
- Adds a Makefile to make building the opnode easier
> opnode: Add Dockerfile/Makefile

- .github/workflows/lint.yml
- meta/README.md
- meta/linting.md
- meta/markdown-style.md
- meta/releases.md
- package.json
- specs/README.md
- specs/deposits.md
- specs/exec-engine.md
- specs/glossary.md
- specs/rollup-node.md
- yarn.lock
This automates TOC building with `yarn lint:toc`, using [doctoc](https://github.com/thlorenz/doctoc). Enforced in CI by checking if the TOC update resulted in any git changes.
Note: I will mess up a TOC intentionally to check if CI works as intended, then roll back the change.
> Doctoc: TOC automation and CI

- opnode/cmd/main.go
- opnode/eth/source.go
- opnode/node/node.go
- opnode/test/system_test.go
L1 Sources are not guaranteed to synchronized with one another and
the rollup node code is not built to re-synchronized the underlying
nodes.
**End User Changes**
The `--l1` option is now only accepts one address rather than being a string slice.
With urfave do see this comment on the string slice flag: https://github.com/urfave/cli/issues/910
> ref impl: Remove combined l1 sources

- .github/workflows/go-ci.yml
This enables tracking code coverage across packages to see an increase
in code coverage due to the e2e test.
**Metadata**
- Fixes #135
> ref impl: Track code coverage across packages

- specs/deposits.md
The spec didn't reflect the `isCreation` field of the `TransactionDeposited` event.
Similarly, we failed to mention that in deposited transactions, the `to` field must be the null address in case of a contract creation.
> Fix deposit specs to account for contract creation

- opnode/eth/id.go
- opnode/l1/source.go
- opnode/rollup/derive/doc.go
- opnode/rollup/derive/invert.go
- opnode/rollup/driver/driver.go
- opnode/rollup/sync/reference.go
- opnode/rollup/sync/start.go
- opnode/rollup/sync/start_test.go
This implements a new sync algorithm for the sequencing work. It extends the the return of the sync start algorithm to include a sequence of L1 blocks that the rollup driver should use (rather than a single block).
The algorithm to find the common block is changed, but the result should be identical.
In addition, the downloader and sync reference have been modified. The downloader has some stubbed methods that the sequencer code uses. The sync reference (and a couple other methods) now more heavily use the `eth.L1Node` /`eth.L2Node` structure.
**Additional context**
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
> ref impl: Sync algorithm for sequencing

- opnode/cmd/main.go
- opnode/eth/heads.go
- opnode/eth/id.go
- opnode/l1/source.go
- opnode/node/node.go
- opnode/rollup/derive/doc.go
- opnode/rollup/derive/invert.go
- opnode/rollup/derive/invert_test.go
- opnode/rollup/derive/payload_attributes.go
- opnode/rollup/driver/driver.go
- opnode/rollup/driver/fake_chain.go
- opnode/rollup/driver/state.go
- opnode/rollup/driver/state_test.go
- opnode/rollup/driver/step.go
- opnode/rollup/sync/reference.go
- opnode/rollup/sync/start.go
- opnode/rollup/sync/start_test.go
- opnode/rollup/types.go
- opnode/test/system_test.go
This PR enables verifiers to use submitted batches to construct the L2 chain. It updates two areas: block derivation and the rollup driver.
This updates the block-derivation to:
* Take a sequencing window as input
* Check the size and consistency of the input
* Derive L2 payloads from possibly out-of-order batches (ignore past/future epochs with overlapping sequencing window)
* Build L2 blocks with fixed block time (fill gaps with empty blocks)
* Limit L2 sequencer-produced blocks to a time-window, do not fill ridiculous out-of-window gaps with empty L2 blocks (by accident or not)
* Force deposits of the epoch (first L1 block of window) into the batch of the first L2 time slot (created if none exists)
This updates the rollup driver:
* Split the rollup driver into `state` …
> ref impl: Verify L2 from batches

- specs/deposits.md
- specs/glossary.md
- specs/rollup-node.md
This PR:
- Updates the rollup node doc:
- define seq window (Fixes #183)
- define seq batches
- update sync (same, but need full seq window of blocks after finding common point)
- misc updates, no more single block output, no deposit-blocks, etc.
- Updates the glossary with sequencing terms, and remove outdated "deposit block"
This PR does not spec the job of the sequencer to *produce* the data, this should probably go into a separate document, similar to how `proposing.md` is split out.
**Metadata**
- Fixes #183 
- Fixes ENG-1978
> Initial sequencing spec

- opnode/rollup/derive/batch.go
- opnode/rollup/derive/batch_test.go
- opnode/rollup/derive/payload_attributes.go
Adds simple batch serialization. This is the simplest version from the specs: `(epoch, timestamp, transactions)`.
It does include the version byte.
A bundle of multiple batches are encoded as an RLP list of these versioned batches, also with version byte. Version 2 may support some type of compression of the bundle of batches.
> ref impl: Add simple batch serialization

- opnode/cmd/main.go
- opnode/eth/id.go
- opnode/flags/flags.go
- opnode/flags/flags_test.go
- opnode/node/config.go
- opnode/node/log.go
- opnode/node/node.go
- opnode/rollup/types.go
- opnode/rollup/types_test.go
- opnode/service.go
- opnode/test/system_test.go
- Split config flags into flags package, like the output submitter does
- Define `--sequencing.enabled` flag to enable sequencer
- Define `--batchsubmitter.key` key flag to load key for batch submitter, from a file with hex-encoded priv key.
- De-duplicate genesis config values
- Properly set L2 genesis time in e2e test
- Load rollup-config (chain params) from json file, a required flag `rollup.config`
- Implement `Check()` for rollup-config, prevent common configuration errors
- Update config / block id / block reference types for JSON encoding
- Move flag parsing and config creation to `opnode` package root (mirrors how output submitter does it), to make it reusable
- Define environment vars for rollup node flags
No rollup-config defaults yet, there's no public testnet to point it to. …
> rollup node config

- packages/contracts/contracts/test/L1Block.t.sol
Fixes basefee test, which previously tested the timestamp field
**Metadata**
Introduced in https://github.com/ethereum-optimism/optimistic-specs/pull/265
> fix: test_basefee now tests basefee

- opnode/l1/source.go
- opnode/rollup/derive/invert_test.go
- opnode/rollup/derive/payload_attributes.go
- opnode/rollup/derive/payload_attributes_test.go
- opnode/rollup/driver/driver.go
- opnode/rollup/driver/step.go
- specs/deposits.md
- specs/rollup-node.md
- bugfix: verify batch does not contain deposit tx type (otherwise sequencers can insert fake deposits into batches)
- sanity-check receipts (most common deposit processing problem in eth2)
- use L2 block-height to ensure uniqueness of deposits when there are multiple L2 blocks with L1 info deposits per L1 block
- update specs (clarify deposit contents, move design text about uniqueness)
- update mock type in tests (l1 info interface has receipt hash now)
- test `ValidBatch` function
> opnode/rollup/derive,specs: fix / harden deposit processing

- .github/workflows/solidity-ci.yml
Splits the workflow into 3 different steps which can run in parallel.
It also allows the checks to pass in the case of a slither error, because slither is way to finnicky, and not all that helpful during active development.
> Parallelize solidity CI checks

- package.json
Changes the markdown linting so that it ignores files in any `node_modules` directory, not just in the root dir.
> linter ignore node_modules in sub dirs

- l2os/config.go
- l2os/drivers/l2output/driver.go
- l2os/flags/flags.go
- l2os/l2_output_submitter.go
- l2os/rollupclient/rollupclient.go
- opnode/test/system_test.go
Using the opnode's `optimism_outputAtBlock` RPC, we can submit l2 output roots.
> l2os: Submit l2 output root via opnode

- opnode/predeploys.go
- packages/contracts/contracts/L2/Withdrawer.sol
- packages/contracts/contracts/test/OptimismPortal.t.sol
- packages/contracts/test/withdrawer.spec.ts
- specs/deposits.md
- specs/withdrawals.md
The Bedrock predeploy addresses are incremented by 1 in order to avoid
conflicts with the system addresses.
> Update predeploy addresses

- opnode/rollup/driver/state.go
This has to be reverted to ensure that the sequencer starts producing
blocks at the same location as the verifier. Sometimes the previous
code would cause reorgs on the sequencer (expected), and sometimes
it would cause a chain split (unexpected and unexplained as of
writing this commit message 4/6/22).
> opnode: Don't start sequencing blocks until past the L1 genesis

- README.md
This:
- Fixes two typos in the readme (`developed`, `convenience`)
- Splits long lines. Markdown will display it the same, but splitting sentences in multiple lines will make future diffs cleaner, as well as making it easy to read on non-wrapping editors.
> readme: fix typos and break lines

- opnode/rollup/driver/state.go
- opnode/rollup/driver/state_test.go
* opnode: Use l2 safe head instead of l2 head
Epochs should be inserted on top of the L2 Safe Head, not the
unsafe head. This was causing problems when a reorg would occur
and the node would start building in the wrong spot.
* opnode: Clear l1WindowBuf on insertEpoch failure
This is done to handle the case that the l1WindowBuf does not start
in the correct location (direct check is difficult with context).
The correct response to that is to clear the window and initialize
it from the correct block.
> opnode: Fix L1WindowBuf management

- opnode/rollup/driver/step.go
The NoTxPool flag was incorrectly set to falses in the InsertEpoch
function.
> opnode: Fix bug in block creation

- opnode/rollup/derive/payload_attributes.go
- opnode/rollup/derive/payload_attributes_test.go
- opnode/test/system_test.go
The ordering of `mint, value` was switched to be `value, mint`
when parsing emitted logs. This allows users to control their
mint rather than using `msg.value` which is being fed directly
into the event.
Thanks to Mofi (Inphi) for finding this.
> opnode: Don't allow arbitrary mints

- Makefile
Ensures that buildkit is used when building the docker setup so that it is faster, fixes a typo where a tab is used and also prune volumes on devnet down
> ops: fix formatting, add docker buildkit support

- go.mod
- go.sum
- opnode/l1/batching.go
- opnode/l1/batching_test.go
This test makes sure that we do not retry when the parent request fails. We don't, but it wasn't immediately clear.
I also removed a duplicate assertion lib since we're using `testify` everywhere else.
> tests: Add tests for batch requests when the parent request fails

- opnode/l2/api.go
- opnode/l2/source.go
- opnode/rollup/derive/invert.go
- opnode/rollup/driver/driver.go
- opnode/rollup/driver/step.go
Previously there were many issues with encoding/decoding transactions:
- first it would fetch the block
- then it would decode the txs
- then it would encode the txs back, and hash them, to compare the equality of attributes
- then it would compare them
- and then it derived the L1 info from the first block
Instead, we should hide all this from the driver, and expose methods that do the most minimal thing:
- Provide execution payloads when necessary to compare against attributes (on reorgs)
- Provide L2 block ref without doing all tx decoding/encoding work, we only need the first
- Provide a method to compute the L2-block ref from a payload, without fuly decoding the payload. We don't need to go back/forth to fully parsed txs when we're dealing with a payload that we produced with the …
> opnode: don't expose types.Block to driver package, prefer l2.ExecutionPayload

- opnode/internal/testutils/fake_chain.go
- opnode/rollup/driver/state_test.go
- opnode/rollup/sync/start_test.go
- opnode/test/geth.go
- opnode/test/setup.go
- opnode/test/system_test.go
This cleans up test utilities three ways
- Put `FakeChainSource` into it's own package (was split across several usages)
- Pulls out common functions like `waitForTx` in the e2e test
- Cleans up the E2E test initialization to make it easy to run tests
New E2E tests:
* L2 Output Submitter Test
* Test deposits + L2 Transactions
* Test missing batches
> opnode: Test Utilities

- l2os/service.go
- opnode/l1/request_sema.go
- opnode/node/node.go
- opnode/rollup/driver/state.go
- opnode/test/setup.go
This changes the order of shutdowns to be correct (rollup nodes prior to clients) as well as making sure that all ethclients are shut down.
**Metadata**
Fixes https://github.com/ethereum-optimism/optimistic-specs/pull/319
> opnode,l2os: Better lifecycle management

- opnode/rollup/derive/invert_test.go
- opnode/rollup/derive/payload_attributes.go
- opnode/rollup/derive/payload_attributes_test.go
- opnode/rollup/driver/step.go
- opnode/rollup/types.go
- opnode/test/system_test.go
- ops/rollup.json
The contract can be deployed to any address. It is set in the rollup config file.
> opnode: Parameterize deposit contract address

- .github/workflows/devnet-ci.yml
Nightly Foundry releases are kept around for 3 days. This means we cannot be pinning the download link on CI to a specific commit.
Instead, we use the Foundry Toolchain GHA which always uses the latest nightly version.
> fix(ci): use Foundry GHA

- specs/glossary.md
- specs/proposals.md
- specs/withdrawals.md
Updates the specs to match the current implementation of the output root, ie. 
`keccak256(version, stateRoot, withdrawerStorageRoot, latestBlockhash)`
> specs: Update output root derivation

- specs/proposals.md
Changes: 
- `latest_block` -> `latest_block_hash`
- Rewrote to words about hoisting the state_root, which were necessary because of the above change.
> specs: Fix definition of output root

- .circleci/config.yml
We ran into this on the monorepo too. Alpine 3.14 removes the `faccessat2` syscall. This caused "operation not permitted" errors while building. Upgrading Circle's Docker version fixes this. See https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2 for more information.
> ci: Update Docker version in CircleCi

- packages/contracts/.gas-snapshot
- packages/contracts/contracts/L1/abstracts/WithdrawalsRelay.sol
- packages/contracts/contracts/L2/Withdrawer.sol
- packages/contracts/contracts/libraries/Lib_WithdrawalVerifier.sol
- packages/contracts/contracts/test/WithdrawalsRelay.t.sol
Reuse the `WithdrawalVerifier` library in both the L1 and L2 contracts. I figure that we might as well use the same code on both sides of the bridge to ensure that its computed exactly the same way. It does seem to increase gas usage a little bit.
> contracts: reuse code

- Makefile
- ops/devnet-up.sh
- ops/docker-compose.yml
Minor fixes to makefile and devnet-up.sh, to make devnet-down work as expected. Previously the `ops_l2os_1` container wasn't being shut down because it was started separately (presumably because of env var option, but fixed that by passing along the env var in the yml environment definition).
> Makefile,ops: docker compose up instead of run to make devnet-down work

- opnode/test/system_test.go
This enables a more verbose output without having to modify the test
itself. Provide the flag `gethlogs` to see logs from geth.
> opnode/test: Provide flag to access geth logs

- go.mod
- go.sum
- opnode/rollup/derive/invert.go
- opnode/rollup/derive/invert_test.go
- opnode/rollup/derive/payload_attributes.go
- opnode/rollup/driver/step.go
- opnode/test/system_test.go
There are three issues being fixed:
1. Set the `from` field to the correct magic value (found by ToB)
2. Update the L2 EE to provide gas to deposits. Otherwise the
deposit transactions immediatley out of gas and fail.
3. Update the manual ABI encoding to match what solidity expects.
The previous version was similar to packed encodeding, but as
such could not be parsed by solidity.
This also includes a regression test that the parsing of the L1 info
tx and what is recorded in the state for each block matches.
> opnode: Fix L1 Info Transactions

- packages/contracts/contracts/libraries/Lib_WithdrawalVerifier.sol
Use `abi.encode` instead of `abi.encodePacked` to ensure
a constant serialization. `abi.encode` will be sure to
pad the value to its size while `abi.encodePacked` will not
when operating on integers. There should not have been a bug here
because it was being called with a `bytes32`, which should
always be 32 bytes when returned from `abi.encodePacked`.
> contracts: fix abi encoding in proof verification

- go.mod
- go.sum
- opnode/node/config.go
- opnode/node/node.go
- opnode/p2p/config.go
- opnode/p2p/discovery.go
- opnode/p2p/host.go
- opnode/p2p/prepared.go
- opnode/test/setup.go
- opnode/test/system_test.go
This PR implements the next p2p todo: attaching the p2p host and discovery service to the node.
The rollup node config can now be set up with a "prepared" p2p setup, to attach a host to it that's part of a "mock net", so we can test p2p communication in different topologies easily, without attaching to the actual localhost TCP and UDP interfaces etc.
See #163
> opnode: attach p2p host and discovery to rollup node, update e2e test

- opnode/l1/source.go
- opnode/rollup/driver/state.go
This is an issue ToB identified (issue #8). What happens is that
the ethereum.NotFound error would never be returned, but in general
if there is an error in the lookup, the state loop should keep
going.
This also properly wrap errors in l1/source.go.
Note: There is an argument for halting L2 block production if it cannot
find the next L1 origin; however, it should be clearly communicated with
an error.
**Metadata**
- Fixes: ENG-2127
> opnode: Fix Incorrect error handling when creating an L2 block

- specs/deposits.md
The link is wrong because the contract has been moved inside the `abstracts` directory
> fix: DepositFeed.sol link

- op-node/flags/p2p_flags.go
- op-node/node/node.go
- op-node/p2p/config.go
- op-node/p2p/discovery.go
- op-node/p2p/host_test.go
- op-node/p2p/node.go
- op-node/p2p/prepared.go
- op-node/p2p/rpc_server.go
- specs/rollup-node-p2p.md
Implements:
- ENR entry (chain ID and version)
- Background process to do random DHT walk, filter nodes, and add to the peerstore
- Background process to select random, not connected, peers and connect to them
- Discovery test: `A` is the bootnode, `B` and `C` find each other via `A`
> P2P discovery
