ethereum-optimism/optimistic-specs

- components/rollup_node.md
Adds an initial spec for the rollup node.
> Initial rollup node spec

- overview.md
Adding a quick link to the statechannels dispute game implementation for improved visibility.
> Add link to dispute game repo

- components/rollup_node.md
Update some inconsistent formatting in the specs as well as some typos.
> fix: typos and make newline usage consistent

- components/rollup_node/block_derivation.md
- glossary.md
A new file glossary.md, which is a first attempt at compiling and clarifying the jargon in the spec.
> Add glossary.md

- opnode/l2/driver.go
Deposit transactions were not unique when multiple are emitted by the same L1 transaction.
The fix changes the tx-index to match the deposit-index within the block (the L1-info tx that is prepended and not emitted based on a log gets a different special value).
We may change this later, the specs skip over uniqueness of deposit transaction hashes, this is just for end-to-end test 0.
> block derivation ref impl: Tx index fix (staging)

- packages/contracts/contracts/L2/L1Block.sol
- packages/contracts/test/L2/L1Block.spec.ts
Addresses the unimplemented test in #92 and Fixes #103. 
Also fixes some formatting warnings that slipped through.
> Add missing auth test to L1Block spec

- README.md
- specs/glossary.md
- specs/rollup-node.md
> s/Optimistic Ethereum/Optimism

- .gitignore
- packages/contracts/contracts/test/DummyContract.sol
- packages/contracts/test/L1/DepositFeed.spec.ts
1. Adds a return value check in the Dummy contract used for testing Deposits made by a contract.
2. This led me to identify a test that was passing incorrectly.
3. And I added two more test cases that were lacking.
> Fix Deposit Feed test

- meta/linting.md
Short & sweet PR to explain how to install `lychee` for linting links.
Merging this tomorrow if there is not feedback by then!
> Add lychee information to meta/linting.md

- meta/README.md
- meta/releases.md
> Document release process

- specs/rollup-node.md
I forgot to do this when updating the rollup node spec PR.
> add syntax highlighting to pseudocode

- .github/workflows/go-ci.yml
Was previously using a matrix form without a matrix being defined.
Defaulted to go 1.15. This was causing problems with building. (thank you
https://twitter.com/alexellisuk/status/1363588781316661248?lang=en)
> Update golang version to 1.17 for CI

- opnode/bss/submitter.go
> ref impl: Simple batch submitter

- README.md
We haven't been running those for a while, and someone did ask me about it. Let's add it back when we actually start doing them again.
> remove R&D calls

- .github/workflows/go-ci.yml
- .github/workflows/markdown-ci.yml
- .github/workflows/solidity-ci.yml
- packages/contracts/README.md
- packages/contracts/contracts/L1/L2OutputOracle.sol
- packages/contracts/contracts/L1/MockL2OutputOracle.sol
- specs/README.md
- specs/glossary.md
- specs/proposals.md
- specs/rollup-node.md
Adds a spec of the L2OS implemented in #179.
> specs: Add L2 output submitter service

- opnode/bss/submitter.go
Rely on intrinisic gas (which can be computed exactly) rather than
using gas estimation.
Adds commented out code to manage the nonce manually. I think that
there was a race between gas estimation and nonce handling which
previously caused problems. If problems continue, it makes sense
to switch over to more manual nonce management.
> opnode: Speed up bss

- ops/entrypoint.sh
Exposes the debug api via http for transaction tracing
> feat: expose debug http api

- packages/contracts/tasks/deposits.ts
Clean up the hardhat task so that it can be more flexible
> hardhat: clean up the hardhat deposit task

- opnode/rollup/derive/payload_attributes.go
- opnode/test/setup.go
- opnode/test/system_test.go
```diff
- 0x4242424242424242424242424242424242424242
+ 0x4200000000000000000000000000000000000015
```
> Fix address of the L1 Block Attributes contracts

- opnode/rollup/driver/step.go
Previously we assumed that every deposit would be included in the L2
block. However, the L2 execution engine removes depoists that are
not valid. As such the number of deposits submitted to the execution
engine could be greater than the number of transactions returned
causing a panic.
This fixes the issue by counting the number of deposits returned
and using that to slice the payload transactions for batch submission.
(Deposits are not submitted in batches and instead read directly from L1).
> opnode: Fix possible panic in sequencer batch creation

- opnode/rollup/sync/start.go
This fixes the bug outlined here: https://github.com/ethereum-optimism/optimistic-specs/pull/353#discussion_r846131762, and adds a lot of comments + improves code structure to make the algorithm easier to understand.
> Fix sync-start bug + improve sync-start comments

- ops/Dockerfile.l2
- package.json
- packages/contracts/helpers/index.ts
- packages/contracts/package.json
- packages/contracts/tasks/deposits.ts
- packages/contracts/test/helpers.spec.ts
- packages/contracts/yarn.lock
Updates the deposit UX to work with:
- https://github.com/ethereum-optimism/reference-optimistic-geth/pull/9
- https://github.com/ethereum-optimism/optimistic-specs/pull/351
Can confirm that it works and the UX is a lot better
> feat: deposit tx js helpers

- opnode/rollup/sync/start.go
- specs/deposits.md
- specs/rollup-node.md
Fix a broken link, a factual mistake and a weird terminology term.
> small fixes

- ops/entrypoint.sh
Allow variable genesis file path and ports.
> Update reference geth entrypoint with variable parameters

- opnode/Makefile
- opnode/cmd/main.go
- opnode/node/api.go
- opnode/node/server_test.go
- opnode/version/version.go
> Add version RPC
